### ISSUE TITLE
Sir, how do I generate .pickle files for my dataset, thank you very much  

### ISSUE THREAD

**Issue by xsyzka** [MKLab-ITI/ndvr-dml#25]

**Comment by gkordo** [comment]
See the #20 issue.
Unfortunately, there is no standard process to generate a similar file cause I did that for each dataset independently.
You might be able to use the same format as the annotation of [CC_WEB_VIDEO](http://vireo.cs.cityu.edu.hk/webvideo/) dataset, in order to generate your `.pickle` files.
